CREATE TABLE IF NOT EXISTS "purchase_cart_smaller" AS
SELECT
    DISTINCT ORDER_ID,
    SHOP,
    ITEM_ID,
    ITEM_DELIVERY_ID,
    DELIVERY_CLOSE_TIME,
    DELIVERY_DISPATCH_DATE,
    DELIVERY_DISPATCH_TIME,
    IFF(
        DELIVERY_LAST_CUSTOMER_DELIVERY_DATE IS NULL,
        DELIVERY_DELIVERY_DATE:: DATE,
        DELIVERY_LAST_CUSTOMER_DELIVERY_DATE:: DATE
    ) AS DELIVERY_LAST_CUSTOMER_DELIVERY_DATE,
    DELIVERY_TS_TRANSPORT_ID
FROM "purchase_cart"
WHERE ITEM_TYPE != 'MARKETPLACE';